trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  kubernetesServiceConnection: '<your-service-connection-name>'
  aksClusterName: '<your-aks-cluster-name>'
  aksResourceGroup: '<your-resource-group-name>'
  namespace: 'default'

stages:
- stage: Deploy
  jobs:
  - job: DeployToAKS
    steps:
    - task: Kubernetes@1
      displayName: 'Deploy to AKS'
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: $(kubernetesServiceConnection)
        azureResourceGroup: $(aksResourceGroup)
        kubernetesCluster: $(aksClusterName)
        namespace: $(namespace)
        command: 'apply'
        useConfigurationFile: true
        configuration: '$(Pipeline.Workspace)/deployment.yaml'