apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: django
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: django
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: django
    spec:
      containers:
        - args:
            - python
            - ./django_app/myproject/manage.py
            - runserver
            - 0.0.0.0:8001
          env:
            - name: MYSQL_DATABASE
              value: QAsportartikelen
            - name: MYSQL_HOST
              value: db
            - name: MYSQL_PASSWORD
              value: QApassword
            - name: MYSQL_USER
              value: QAuser
          image: django
          name: django
          ports:
            - containerPort: 8001
              protocol: TCP
          volumeMounts:
            - mountPath: /django_app
              name: django-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: django-cm0
          name: django-cm0
