version: "3"

services:
  db:
    image: mariadb
    restart: always
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_USER: QAuser                  # non-root user (optional)
      MYSQL_PASSWORD: QApassword 
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'QAsportarticles'
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - backend
      - monitoring

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_USER: QAuser
      MYSQL_PASSWORD: QApassword
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8090:80"
    depends_on:
      - db
    networks:
      - backend

  fastapi_app:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile
    command: python3 main.py
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=QAuser
      - MYSQL_PASSWORD=QApassword
      - MYSQL_DATABASE=QAsportarticles
    networks:
      - backend

  django:
    build:
      context: ./django_app
      dockerfile: Dockerfile
    command: python ./django_app/myproject/manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=QAuser
      - MYSQL_PASSWORD=QApassword
      - MYSQL_DATABASE=QAsportarticles
    volumes:
      - .:/django_app
    networks:
      - backend

  grafana:
    build: ./grafana
    ports:
      - "4000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    depends_on:
      - db
    networks:
      - monitoring

# Networks
networks:
  backend:
    driver: bridge
  monitoring:
    driver: bridge

volumes:
  grafana-data:
    driver: "local"
