apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: fastapi-app
  name: fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fastapi-app
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: fastapi-app
    spec:
      containers:
        - args:
            - python3
            - main.py
          env:
            - name: MYSQL_DATABASE
              value: QAsportartikelen
            - name: MYSQL_HOST
              value: db
            - name: MYSQL_PASSWORD
              value: QApassword
            - name: MYSQL_USER
              value: QAuser
          image: fastapi-app
          name: fastapi-app
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
