apiVersion: v1
data:
  datasource.yaml: |
    apiVersion: 1

    datasources:
      - name: mariadb-datasource
        uid: mariadb-ds
        orgId: 1
        type: mysql
        access: proxy
        url: db:3306
        database: QAsportartikelen
        user: "QAuser"
        secureJsonData:
          password: "QApassword"
        jsonData:
          tlsAuth: false
          tlsAuthWithCACert: false
          maxOpenConns: 10
          maxIdleConns: 10
          connMaxLifetime: 14400
        isDefault: true

      # - name: InfluxDB
      #   uid: influxDB
      #   orgId: 1
      #   type: influxdb
      #   access: proxy
      #   url: http://influxdb:8086
      #   user: myusername
      #   password: passwordpasswordpassword
      #   jsonData:
      #     version: Flux
      #     organization: myorg
      #     defaultBucket: mybucket
      #     tlsSkipVerify: true
      #   secureJsonData:
      #     token: mytoken
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: grafana
  name: grafana-cm1
