apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: frontend-django
  name: frontend-django
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend-django
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: frontend-django
    spec:
      containers:
        - args:
            - python
            - ./frontend-django/myproject/manage.py
            - runserver
            - 0.0.0.0:8001
          env:
            - name: MYSQL_DATABASE
              value: QAsportarticles
            - name: MYSQL_HOST
              value: db
            - name: MYSQL_PASSWORD
              value: QApassword
            - name: MYSQL_USER
              value: QAuser
          image: frontend-django
          name: frontend-django
          ports:
            - containerPort: 8001
              protocol: TCP
          volumeMounts:
            - mountPath: /frontend-django
              name: frontend-django-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: frontend-django-cm0
          name: frontend-django-cm0
