apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: middleware-fastapi
  name: middleware-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: middleware-fastapi
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: middleware-fastapi
    spec:
      containers:
        - args:
            - python3
            - main.py
          env:
            - name: MYSQL_DATABASE
              value: QAsportarticles
            - name: MYSQL_HOST
              value: db
            - name: MYSQL_PASSWORD
              value: QApassword
            - name: MYSQL_USER
              value: QAuser
          image: middleware-fastapi
          name: middleware-fastapi
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
