apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: phpmyadmin
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: phpmyadmin
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: phpmyadmin
    spec:
      containers:
        - env:
            - name: MYSQL_PASSWORD
              value: QApassword
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_USER
              value: QAuser
            - name: PMA_HOST
              value: db
          image: phpmyadmin/phpmyadmin
          name: phpmyadmin
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
