name: Sync to Azure sandbox Beni

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  push-to-azure:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4

      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
  
      - name: Add Azure DevOps remote
        run: git remote add azure https://TechlabQA:${{ secrets.AZUREPATSANDBOXBENISYNC }}@dev.azure.com/TechlabQA/ZandbakBeni/_git/ZandbakBeni
  
      - name: Push to Azure DevOps
        run: git push azure main
        env:
          AZURE_PAT: ${{ secrets.AZUREPATSANDBOXBENISYNC }}
